stages:
  - delivery
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: never
    - when: always

variables:
  MPSA_APP_VERSION: "0.0.3"
  KUBE_NAMESPACE: "bernard-services"
  BUILDAH_VERSION: "latest"

delivery_image:
  stage: delivery
  image:
    name: quay.io/containers/buildah:$BUILDAH_VERSION
  script:
    - buildah login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      buildah bud --format docker
      -f $CI_PROJECT_DIR/Dockerfile
      -t $CI_REGISTRY_IMAGE:$MPSA_APP_VERSION
      $CI_PROJECT_DIR
    - buildah push $CI_REGISTRY_IMAGE:$MPSA_APP_VERSION docker://$CI_REGISTRY_IMAGE:$MPSA_APP_VERSION
  after_script:
    - buildah logout $CI_REGISTRY

deploy_mpsavoting:
  stage: deploy
  image: devth/helm:v3.8.0
  environment:
    name: production
  script:
    - >
      helm upgrade
      --install
      --cleanup-on-fail
      --atomic
      --create-namespace
      --namespace $KUBE_NAMESPACE
      --set image.repository=$CI_REGISTRY_IMAGE
      --set image.tag=$MPSA_APP_VERSION
      --set registrySecret.registry=$CI_REGISTRY
      --set registrySecret.username=$CI_DEPLOY_USER
      --set registrySecret.password=$CI_DEPLOY_PASSWORD
      --set gitlab.env=${CI_ENVIRONMENT_SLUG}
      --set gitlab.app=${CI_PROJECT_PATH_SLUG}
      mpsavoting
      ./charts/mpsavoting
      --timeout 15m