apiVersion: v1
kind: Service
metadata:
  name: {{ include "mpsavoting.fullname" . }}
  labels:
    {{- include "mpsavoting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "mpsavoting.selectorLabels" . | nindent 4 }}
